# Generated by Django 3.0.5 on 2021-05-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupation', models.CharField(blank=True, max_length=50)),
                ('Hometown', models.CharField(blank=True, max_length=50)),
                ('Current_City', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('pintrest', models.URLField(blank=True, null=True)),
                ('tumblr', models.URLField(blank=True, null=True)),
                ('total_views', models.IntegerField(default=0)),
                ('fav_count', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
                ('tag_count', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
