# Generated by Django 3.0.5 on 2021-05-14 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_alias', models.TextField(blank=True)),
                ('iconserver', models.IntegerField(blank=True, default=0)),
                ('iconfarm', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('members', models.IntegerField(blank=True, default=1)),
                ('pool_count', models.IntegerField(blank=True, default=0)),
                ('topic_count', models.IntegerField(blank=True, default=0)),
                ('privacy', models.IntegerField(choices=[(1, 'private'), (2, 'invitation_only'), (3, 'public')])),
                ('lang', models.TextField(blank=True)),
                ('roles_member', models.TextField(blank=True, default='Member')),
                ('roles_admin', models.TextField(blank=True, default='Admin')),
                ('limit_photo_opt_out', models.IntegerField(blank=True, default=0)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateactivity', models.IntegerField(blank=True, default=0)),
                ('eighteenplus', models.BooleanField()),
                ('invitation_only', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(blank=True, default=False)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_founder', models.BooleanField(blank=True, default=False)),
                ('user_group_prefs', models.TextField(blank=True)),
                ('blast_content', models.TextField(blank=True)),
                ('blast_date_blast_added', models.TextField(blank=True)),
                ('blast_user_id', models.CharField(blank=True, max_length=100)),
                ('throttle_count', models.IntegerField(blank=True, default=0)),
                ('throttle_mode', models.TextField(blank=True)),
                ('throttle_remaining', models.TextField(blank=True)),
                ('restrictions_photos_ok', models.BooleanField(blank=True, default=True)),
                ('restrictions_videos_ok', models.BooleanField(blank=True, default=True)),
                ('restrictions_images_ok', models.BooleanField(blank=True, default=True)),
                ('restrictions_art_ok', models.BooleanField(blank=True, default=True)),
                ('restrictions_safe_ok', models.BooleanField(blank=True, default=True)),
                ('restrictions_restricted_ok', models.BooleanField(blank=True, default=False)),
                ('restrictions_has_geo', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('count_replies', models.IntegerField(blank=True, default=0)),
                ('datecreate', models.DateTimeField(auto_now=True)),
                ('datelastpost', models.DateTimeField(blank=True)),
                ('last_reply', models.DateTimeField(blank=True)),
                ('lastedit', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_topic', to='group.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('datecreate', models.DateTimeField(auto_now=True)),
                ('lastedit', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_owner', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_topic_reply', to='group.topic')),
            ],
        ),
    ]
