# Generated by Django 3.0.5 on 2021-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210501_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.AddField(
            model_name='account',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
