# Generated by Django 3.0.5 on 2021-05-08 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.PositiveIntegerField(blank=True, max_length=30)),
                ('secret', models.PositiveIntegerField(blank=True, max_length=15)),
                ('server', models.PositiveIntegerField(blank=True, max_length=15)),
                ('farm', models.PositiveIntegerField(blank=True, max_length=15)),
                ('photos', models.PositiveIntegerField(default=1)),
                ('count_views', models.PositiveIntegerField(default=0)),
                ('count_comments', models.PositiveIntegerField(default=0)),
                ('count_videos', models.PositiveIntegerField(default=0)),
                ('can_comment', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility_can_see_set', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photoset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='commentss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=15)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photoset_comments', to=settings.AUTH_USER_MODEL)),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='photosets.sets')),
            ],
        ),
    ]
